LOAD DATA LOCAL INFILE 'user.del' INTO TABLE User 
FIELDS TERMINATED BY '|*|'; 

LOAD DATA LOCAL INFILE 'item.del' INTO TABLE Item 
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bid.del' INTO TABLE Bid 
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'category.del' INTO TABLE Category 
FIELDS TERMINATED BY '|*|' ;
